export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const LAY_THONG_TIN_NGUOI_DUNG = "LAY_THONG_TIN_NGUOI_DUNG";
export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG = "LAY_DANH_SACH_LOAI_NGUOI_DUNG";
export const LAY_THONG_TIN_NGUOI_DUNG_CAP_NHAT =
	"LAY_THONG_TIN_NGUOI_DUNG_CAP_NHAT";
