export const LAY_THONG_TIN_PHONG_VE = "LAY_THONG_TIN_PHONG_VE";
export const DAT_GHE = "DAT_GHE";
export const DAT_VE_HOAN_TAT = "DAT_VE_HOAN_TAT";

export const CHUYEN_TAB = "CHUYEN_TAB";
export const CHANGE_TAB_ACTIVE = "CHANGE_TAB_ACTIVE";

export const LAY_DANH_SACH_GHE_KHACH_DANG_DAT =
	"LAY_DANH_SACH_GHE_KHACH_DANG_DAT";
