export const LAY_THONG_TIN_HE_THONG_RAP = "LAY_THONG_TIN_HE_THONG_RAP";
export const LAY_THONG_TIN_HE_THONG_RAP_FOOTER =
	"LAY_THONG_TIN_HE_THONG_RAP_FOOTER";

export const LAY_THONG_TIN_LICH_CHIEU_PHIM = "LAY_THONG_TIN_LICH_CHIEU_PHIM";
